//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOLZANO.DataMining.RestaurantsAndConsumers.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ele\\Documents\\GitHub\\DataMining.Project.RestaurantsConsumers\\BOLZANO.Dat" +
            "aMining.RestaurantsAndConsumers\\Database\\userprofile.csv")]
        public string userProfilePath {
            get {
                return ((string)(this["userProfilePath"]));
            }
            set {
                this["userProfilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ele\\Documents\\GitHub\\DataMining.Project.RestaurantsConsumers\\BOLZANO.Dat" +
            "aMining.RestaurantsAndConsumers\\Database\\geoplaces2.csv")]
        public string geoplaces2Path {
            get {
                return ((string)(this["geoplaces2Path"]));
            }
            set {
                this["geoplaces2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ele\\Documents\\GitHub\\DataMining.Project.RestaurantsConsumers\\BOLZANO.Dat" +
            "aMining.RestaurantsAndConsumers\\Database\\rating_final.csv")]
        public string rating_finalPath {
            get {
                return ((string)(this["rating_finalPath"]));
            }
            set {
                this["rating_finalPath"] = value;
            }
        }
    }
}
